name: Maison Hub Lab
version: 0.6.1
slug: maisonhub
description: Prototype local de messages, réservé aux administrateurs Home Assistant
arch:
  - aarch64
init: false
startup: application
boot: manual
ingress: true
ingress_port: 8099
panel_icon: mdi:home-heart
panel_title: Maison Hub Lab
panel_admin: true
stage: experimental
map:
  - type: data
    read_only: false
